name: Label Issues (Script Injection Example)
on:
  issues:
    types:
      - opened
jobs:
  assign-label:
    runs-on: ubuntu-latest
    env:
      Title: ${{ github.event.issue.title }}
    steps:
      - name: Assign label
        run: |
          if [[ "$Title" == *"bug"* ]]; then
          echo "Issue is about a bug!"
          else
          echo "Issue is not about a bug"
          fi
